### PR TITLE
Pinning the web linked data

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by benfrancis** [comment]
This is a great start. I couldn't get it to work though, I kept getting this error when tapping a pin:

```
E/GeckoConsole(19307): [JavaScript Error: "TypeError: cards[1].querySelector(...) is null" {file: "app://system.gaiamobile.org/js/app_chrome.js" line: 1052}]
```

From what I can see of the code I don't think this is quite enough to provide compelling examples of Linked Data in pinned cards though. The idea is that we want to show how different types of information can be presented differently with different card templates. E.g. for a photo just show the photo, for a place show the place name and address, for a contact show key contact details. With the code here it seems we basically still display everything in the same way?

**Comment by mikehenrty** [comment]
Ok, I removed the circular icons, and fixed the onclick problem. The error `TypeError: cards[1].querySelector(...)` I think was unrelated, but if you see it again please let me know. @benfrancis what do you think now?

**Comment by benfrancis** [comment]
Sounds good. I can't test this because I don't have your Gecko patch and the pastebin has expired! But I'm going to go ahead and merge it, thanks.

**Comment by benfrancis** [comment]
Hmm sorry I had to back this out, still seeing the regression which causes tapping the site pin in browser chrome to do nothing, and alberto confirmed :(

**Pull request merged**
