### PR TITLE
Add gaia handlers for og: meta change events, consolidating to schema…

### PR DESCRIPTION
**Pull request by mikehenrty**
…change, adding to places metadata

### CODE REVIEW

**Comment by mikehenrty** [comment]
@benfrancis r?

Let me know if you want to see my gecko changes too.

**Comment by benfrancis** [comment]
Cool!

Nit: Any chance we can call this "linkedData" rather than "schemaData"?

Where can I find the Gecko patch (just out of curiosity)?

**Comment by mikehenrty** [comment]
@benfrancis done! i think this is ready to merge

**Comment by benfrancis** [comment]
Great! Thanks.

**Pull request merged**
